# Generated by Django 5.0.10 on 2024-12-06 23:15
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [TrigramExtension()]
